---
label: Products
hide_body: false
fields:
- name: date
  type: datetime
  label: Fecha
  description: ''
  config:
    required: true
    date_format: DD/MM/YYYY
    time_format: 
    display_utc: false
  default: now
- name: title
  type: text
  config:
    required: true
    max: '60'
  label: Título
  description: Ingresa el título del producto
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Descripción
  description: Corta descripción del producto
- name: category
  type: select
  default: Piedras preciosas
  config:
    required: true
    options:
    - Baterías
    - Celulares
    - Accesorios
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Categoría
  description: Selecciona la categoría del producto
- name: unit_price
  type: text
  config:
    required: true
  label: Precio
  description: Precio del producto sin "$" o "COP"
- name: images
  type: image_gallery
  config: {}
  label: Fotos
  description: Fotos del producto
  showOnly:
    value: false
- name: available
  type: boolean
  label: Producto disponible
  description: Indica si el producto está disponible
  default: true
- name: sellable
  type: boolean
  label: Producto vendible
  description: Productos vendibles tendrán botón de compra en la página
  showOnly:
    field: available
    value: true
- name: payu_purchase_link
  type: text
  config:
    required: false
  label: Link de compra
  description: Link de compra de PayU
  showOnly:
    field: sellable
    value: true
pages:
- content/products/cuarzo-rutilo-de-oro-piedra-natural-215-80-quilates.md
- content/products/nacar-piedra-natural-89-90-quilates.md
- content/products/piedra-preciosa-coral-fosilizado-105-20-quilates.md
- content/products/rosa-del-desierto-piedra-100-natural.md
- content/products/tanzanita-canutillo-piedra-natural-46-20-quilates.md
